function [fitresult, gof] = RCFPolynomialFit_SecondMethod(NetOpticalDensities, DosesValues)
%CREATEFIT(NETOPTICALDENSITIES,DOSESVALUES)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : NetOpticalDensities
%      Y Output: DosesValues
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 28-Nov-2021 17:10:37


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( NetOpticalDensities, DosesValues );

% Set up fittype and options.
ft = fittype( 'P3*x^3 + P2*x^2 + P1*x', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Robust = 'LAR';
opts.StartPoint = [0.964888535199277 0.957506835434298 0.546881519204984];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );



