function [P1, P2, P3, ...
    BackgroundValue,...
    Doses,...
    NetOpticalDensities] = ReadCalibrationDataAndFit(FilePath)
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/cirrone/Dropbox/script_e_software/I-LUCE/RadiochromicAnalysis/CAL_HD-V2_62MeV_Protons_Scanner_ELI/CalibrationDataAndFit.txt
%
% Auto-generated by MATLAB on 25-Dec-2021 19:12:07

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [5, 5; 8, 8; 11, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, "VarName3", "TrimNonNumeric", true);
opts = setvaropts(opts, "VarName3", "ThousandsSeparator", ",");

% Import the data
%FilePath = "/Users/cirrone/Dropbox/script_e_software/I-LUCE/RadiochromicAnalysis/CAL_HD-V2_62MeV_Protons_Scanner_ELI/CalibrationDataAndFit.txt";
CalibrationDataAndFit = readtable(FilePath, opts);

%% Convert to output type
CalibrationDataAndFit = table2array(CalibrationDataAndFit);

%% Clear temporary variables
clear opts

%% Extract from the readed table the fit parameters, the used background 
% value and the two vectors with Dose and the Net Optical Density
%
P1 = CalibrationDataAndFit(1, 1);
P2 = CalibrationDataAndFit(1, 2);
P3 = CalibrationDataAndFit(1, 3);

BackgroundValue = CalibrationDataAndFit(2, 1);

VectorLength = length(CalibrationDataAndFit(:,1));

Doses = CalibrationDataAndFit(3:VectorLength,1);
NetOpticalDensities = CalibrationDataAndFit(3:VectorLength,1);

end